name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.11.1'
      - name: Build
        run: gradle build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: profilescanner
          path: build/libs/profilescanner-1.0.0.jar
